name: fog-drone

on:
  push:
    branches: main
  paths:
    - fog-drone/**

jobs:
  tii-fog-drone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.PACKAGES_USER }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Build tii-fog-drone image and push
        uses: docker/build-push-action@v2
        with:
          context: ./fog-drone/
          file: ./fog-drone/Dockerfile
          push: true
          tags: ghcr.io/tiiuae/tii-fog-drone:latest
