name: mqtt-server

on:
  push:
    branches: main
  paths:
    - mqtt-server/**

jobs:
  tii-mqtt-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.PACKAGES_USER }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Build tii-mqtt-server image and push
        uses: docker/build-push-action@v2
        with:
          context: ./mqtt-server/
          file: ./mqtt-server/Dockerfile
          push: true
          tags: ghcr.io/tiiuae/tii-mqtt-server:latest
